name: Update TV Data from IPTV-API Repo

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行一次
  workflow_dispatch:       # 手动触发

jobs:
  update-tv-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for updates in remote file
        run: |
          curl -o new_zb https://raw.githubusercontent.com/lyliangyuxuan/iptv-api/refs/heads/master/output/user_result.txt
          if [ -f zb ]; then
            if cmp -s zb new_zb; then
              echo "No changes in remote file. Exiting..."
              exit 0
            else
              echo "Changes detected. Updating zb..."
            fi
          fi

      - name: Remove old zb
        run: rm -f zb

      - name: Rename new_zb to zb
        run: mv new_zb zb

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add zb
          git commit -m "Update zb from IPTV-API repo"
          git push
